import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61xBASwU+zL._SX569_.jpg",
    title: "Asus TUF A15 Gaming Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Laptops",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/81tmCrtiRgL._SX569_.jpg",
    title: "Lenovo LOQ 2024 Gaming Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Laptops",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/41eLRC9ZWPL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "HP Victus Gaming Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Laptops",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/41rlpmPrMEL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "Acer Aspire 3 Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Laptops",
    color: "silver",
    category: "Electronics",
  },
  // Mobiles
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61NsPikkMBL._AC_UY327_FMwebp_QL65_.jpg",
    title: "Motorola Edge 60 Fusion",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "blue",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61gGRaXQoGL._AC_UY327_FMwebp_QL65_.jpg",
    title: "IQOO Neo 10",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "red",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61Ony8rgwEL._AC_UY327_FMwebp_QL65_.jpg",
    title: "Iphone 16 Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/71rs4Aer71L._AC_UY327_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy S25 Ultra",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "silver",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61muVCIy-uL._AC_UY327_FMwebp_QL65_.jpg",
    title: "Oneplus 13R",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/81wW3hnaFbL._AC_UY327_FMwebp_QL65_.jpg",
    title: "Nothing Phone 2a",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "white",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/51Ibtg1KESL._AC_UY327_FMwebp_QL65_.jpg",
    title: "Google Pixel 9",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "black",
    category: "Electronics",
  },
  // Headphones
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/71zfpkr4bYL._AC_UY327_FMwebp_QL65_.jpg",
    title: "Goboult Q Over Ear Bluetooth Headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Headphones",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/81ZCn5FcELL._SX466_.jpg",
    title: "Boult x Mustang Q Over Ear Bluetooth Headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Headphones",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61kFL7ywsZS._AC_UY327_FMwebp_QL65_.jpg",
    title: "JBL Tune 510BT Wireless On-Ear Headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Headphones",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/71L70bAl2KL._AC_UY327_FMwebp_QL65_.jpg",
    title: "boAt Rockerz 450 Bluetooth Headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Headphones",
    color: "black",
    category: "Electronics",
  },
  // Clothings
  // Men's
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/71eUwDk8z+L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Allen Solly Men's Cotton Regular Fit Polo T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61dKZK61kfL._AC_UL480_FMwebp_QL65_.jpg",
    title: "koshin Art Silk Full Embroidered Work Kurta for Festive",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/81YxBqTZ+4L._AC_UL480_FMwebp_QL65_.jpg",
    title: "GODFREY Cuban Collar Casual Shirts for Men",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/71ad8PSy5kL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Men's Cotton Shirt | Chinese Collar | Casual | Plain | Full Sleeve | Regular Fit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61n8G12sUML._AC_UL480_FMwebp_QL65_.jpg",
    title: "Men's Cottonblend Oversized Half Sleeve Round Neck Regular Fit T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61MOSsGNBwL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Arvind Solid Twill Formal Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/91kxyUggGbL._AC_UL480_FMwebp_QL65_.jpg",
    title: "BE ACTIV Men's Pure Cotton Lucknowi Kurta",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/513Ya0OZQXL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Peter England Men's Everyday Festive Solid Short Kurta Cotton",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/I/51orCQMpdRL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Fresho Lalbagh Mango - Sindhura 1kg",
    star: <AiFillStar className='rating-star' />,
    reviews: "(324 reviews)",
    prevPrice: "₹159",
    newPrice: "₹131",
    company: "Fresho",
    color: "yellow",
    category: "Groceries",
  },
  {
    img: "https://m.media-amazon.com/images/I/71AyZgZ3bSL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Tata Sampann Unpolished Toor Dal 1kg",
    star: <AiFillStar className='rating-star' />,
    reviews: "(1 review)",
    prevPrice: "₹95",
    newPrice: "₹79",
    company: "Tata Sampann",
    color: "brown",
    category: "Groceries",
  },
  {
    img: "https://m.media-amazon.com/images/I/71iJt-aYbZL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Tata Sampann Unpolished Green Whole Moong 500 g",
    star: <AiFillStar className='rating-star' />,
    reviews: "(12 reviews)",
    prevPrice: "₹99",
    newPrice: "₹86",
    company: "Tata Sampann",
    color: "green",
    category: "Groceries",
  },
  {
    img: "https://m.media-amazon.com/images/I/71s30bA7zeL._AC_UL480_FMwebp_QL65_.jpg",
    title: "India Gate Basmati Rice Classic 5 kg",
    star: <AiFillStar className='rating-star' />,
    reviews: "(4500 reviews)",
    prevPrice: "₹2,050",
    newPrice: "₹1,499",
    company: "India Gate",
    color: "white",
    category: "Groceries",
  },
  {
    img: "https://m.media-amazon.com/images/I/9104JpXbv6L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Aashirvaad Whole Wheat Atta 10 kg",
    star: <AiFillStar className='rating-star' />,
    reviews: "(3000 reviews)",
    prevPrice: "₹560",
    newPrice: "₹499",
    company: "Aashirvaad",
    color: "beige",
    category: "Groceries",
  },
  {
    img: "https://m.media-amazon.com/images/I/61rcMYf0tpL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Tata Simply Better Cold‑Pressed Groundnut Oil 1 L",
    star: <AiFillStar className='rating-star' />,
    reviews: "(2742 reviews)",
    prevPrice: "₹350",
    newPrice: "₹301",
    company: "Tata Simply Better",
    color: "amber",
    category: "Groceries",
  },
  {
    img: "https://m.media-amazon.com/images/I/71LNfaqfh6L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Happilo California Almonds 500 g",
    star: <AiFillStar className='rating-star' />,
    reviews: "(73431 reviews)",
    prevPrice: "₹660",
    newPrice: "₹576",
    company: "Happilo",
    color: "brown",
    category: "Groceries",
  },
  {
    img: "https://m.media-amazon.com/images/I/81rUSGASgQL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Kellogg's Muesli Fruit Nut & Seeds 750 g",
    star: <AiFillStar className='rating-star' />,
    reviews: "(25323 reviews)",
    prevPrice: "₹399",
    newPrice: "₹358",
    company: "Kellogg's",
    color: "multicolor",
    category: "Groceries",
  },
  {
    img: "https://m.media-amazon.com/images/I/61+Zq4NHMNL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Parry’s White Label Sugar 1 kg",
    star: <AiFillStar className='rating-star' />,
    reviews: "(20407 reviews)",
    prevPrice: "₹45",
    newPrice: "₹39",
    company: "Parry’s",
    color: "white",
    category: "Groceries",
  },
  {
    img: "https://m.media-amazon.com/images/I/61aB4oiy9NL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Tata Sampann Chana Dal Fine Besan 1 kg",
    star: <AiFillStar className='rating-star' />,
    reviews: "(14472 reviews)",
    prevPrice: "₹129",
    newPrice: "₹112",
    company: "Tata Sampann",
    color: "yellow",
    category: "Groceries",
  },
  {
    img: "https://m.media-amazon.com/images/I/71hI+XoAYPL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Jacklin Upholstered King Bed",
    star: <AiFillStar className='rating-star' />,
    reviews: "(87 reviews)",
    prevPrice: "₹45,000",
    newPrice: "₹39,910",
    company: "Durian",
    color: "grey",
    category: "Furniture",
  },
  {
    img: "https://m.media-amazon.com/images/I/413HQpObrkL._AC_UL480_FMwebp_QL65_.jpg",
    title: "IKEA GURSKEN Bedroom Set (5‑piece)",
    star: <AiFillStar className='rating-star' />,
    reviews: "(54 reviews)",
    prevPrice: "₹30,000",
    newPrice: "₹27,550",
    company: "IKEA",
    color: "white",
    category: "Furniture",
  },
  {
    img: "https://m.media-amazon.com/images/I/81SaTpHgTHL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Home Centre Helios Bravo Roxy Queen Bed",
    star: <AiFillStar className='rating-star' />,
    reviews: "(120 reviews)",
    prevPrice: "₹39,999",
    newPrice: "₹31,999",
    company: "Home Centre",
    color: "green",
    category: "Furniture",
  },
  {
    img: "https://m.media-amazon.com/images/I/81MBcCfBx4L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Home Centre Helios Alton Study Desk",
    star: <AiFillStar className='rating-star' />,
    reviews: "(55 reviews)",
    prevPrice: "₹9,999",
    newPrice: "₹7,999",
    company: "Home Centre",
    color: "brown",
    category: "Furniture",
  },
  {
    img: "https://m.media-amazon.com/images/I/71kITJJEGxL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Home Centre Helios Alton Book Shelf",
    star: <AiFillStar className='rating-star' />,
    reviews: "(80 reviews)",
    prevPrice: "₹10,999",
    newPrice: "₹8,999",
    company: "Home Centre",
    color: "white",
    category: "Furniture",
  },
  {
    img: "https://m.media-amazon.com/images/I/61d+QluYQgL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Home Centre Helios 12‑Pair Shoe Cabinet",
    star: <AiFillStar className='rating-star' />,
    reviews: "(45 reviews)",
    prevPrice: "₹12,999",
    newPrice: "₹9,999",
    company: "Home Centre",
    color: "white",
    category: "Furniture",
  },
  {
    img: "https://m.media-amazon.com/images/I/81uobrUcIbL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Home Centre Seaford Faux Leather Recliner Chair",
    star: <AiFillStar className='rating-star' />,
    reviews: "(65 reviews)",
    prevPrice: "₹79,998",
    newPrice: "₹69,998",
    company: "Home Centre",
    color: "brown",
    category: "Furniture",
  },
  {
    img: "https://m.media-amazon.com/images/I/914Svzgb2AL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Home Centre Denver Swivel Coffee Table",
    star: <AiFillStar className='rating-star' />,
    reviews: "(38 reviews)",
    prevPrice: "₹29,998",
    newPrice: "₹24,999",
    company: "Home Centre",
    color: "white",
    category: "Furniture",
  },
  {
    img: "https://m.media-amazon.com/images/I/71+hQNlpliL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Magnolia Home Comma Coffee Table",
    star: <AiFillStar className='rating-star' />,
    reviews: "(20 reviews)",
    prevPrice: "₹75,000",
    newPrice: "₹68,000",
    company: "Magnolia Home",
    color: "oak",
    category: "Furniture",
  },
  {
    img: "https://m.media-amazon.com/images/I/61qCiQUbSTL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Magnolia Home Bella Coffee Table",
    star: <AiFillStar className='rating-star' />,
    reviews: "(15 reviews)",
    prevPrice: "₹63,000",
    newPrice: "₹56,000",
    company: "Magnolia Home",
    color: "walnut",
    category: "Furniture",
  }


  
];

export default data;
