import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61xBASwU+zL._SX569_.jpg",
    title: "Asus TUF A15 Gaming Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Laptops",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/81tmCrtiRgL._SX569_.jpg",
    title: "Lenovo LOQ 2024 Gaming Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Laptops",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/41eLRC9ZWPL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "HP Victus Gaming Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Laptops",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/41rlpmPrMEL._SX300_SY300_QL70_FMwebp_.jpg",
    title: "Acer Aspire 3 Laptop",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Laptops",
    color: "silver",
    category: "Electronics",
  },
  // Mobiles
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61NsPikkMBL._AC_UY327_FMwebp_QL65_.jpg",
    title: "Motorola Edge 60 Fusion",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "blue",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61gGRaXQoGL._AC_UY327_FMwebp_QL65_.jpg",
    title: "IQOO Neo 10",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "red",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61Ony8rgwEL._AC_UY327_FMwebp_QL65_.jpg",
    title: "Iphone 16 Pro",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/71rs4Aer71L._AC_UY327_FMwebp_QL65_.jpg",
    title: "Samsung Galaxy S25 Ultra",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "silver",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61muVCIy-uL._AC_UY327_FMwebp_QL65_.jpg",
    title: "Oneplus 13R",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/81wW3hnaFbL._AC_UY327_FMwebp_QL65_.jpg",
    title: "Nothing Phone 2a",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "white",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/51Ibtg1KESL._AC_UY327_FMwebp_QL65_.jpg",
    title: "Google Pixel 9",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Mobiles",
    color: "black",
    category: "Electronics",
  },
  // Headphones
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/71zfpkr4bYL._AC_UY327_FMwebp_QL65_.jpg",
    title: "Goboult Q Over Ear Bluetooth Headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Headphones",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/81ZCn5FcELL._SX466_.jpg",
    title: "Boult x Mustang Q Over Ear Bluetooth Headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Headphones",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61kFL7ywsZS._AC_UY327_FMwebp_QL65_.jpg",
    title: "JBL Tune 510BT Wireless On-Ear Headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Headphones",
    color: "black",
    category: "Electronics",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/71L70bAl2KL._AC_UY327_FMwebp_QL65_.jpg",
    title: "boAt Rockerz 450 Bluetooth Headphones",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Headphones",
    color: "black",
    category: "Electronics",
  },
  // Clothings
  // Men's
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/71eUwDk8z+L._AC_UL480_FMwebp_QL65_.jpg",
    title: "Allen Solly Men's Cotton Regular Fit Polo T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61dKZK61kfL._AC_UL480_FMwebp_QL65_.jpg",
    title: "koshin Art Silk Full Embroidered Work Kurta for Festive",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/81YxBqTZ+4L._AC_UL480_FMwebp_QL65_.jpg",
    title: "GODFREY Cuban Collar Casual Shirts for Men",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/71ad8PSy5kL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Men's Cotton Shirt | Chinese Collar | Casual | Plain | Full Sleeve | Regular Fit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61n8G12sUML._AC_UL480_FMwebp_QL65_.jpg",
    title: "Men's Cottonblend Oversized Half Sleeve Round Neck Regular Fit T-Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/61MOSsGNBwL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Arvind Solid Twill Formal Shirt",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/91kxyUggGbL._AC_UL480_FMwebp_QL65_.jpg",
    title: "BE ACTIV Men's Pure Cotton Lucknowi Kurta",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  {
    img: "https://m.media-amazon.com/images/W/MEDIAX_1215821-T1/images/I/513Ya0OZQXL._AC_UL480_FMwebp_QL65_.jpg",
    title: "Peter England Men's Everyday Festive Solid Short Kurta Cotton",
    star: <AiFillStar className="rating-star" />,
    reviews: "(1195 reviews)",
    prevPrice: "$800,00",
    newPrice: "$650",
    company: "Clothing",
    color: "black",
    category: "Clothing",
  },
  
];

export default data;
